// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: '/api',
  envName: 'PROD',
  backend_api_url: 'https://backend.lotusfx.co/',
  GEO_COOKIE_API: 'https://geolocation-db.com/',
};
